# -*- coding: utf-8 -*-
"""demo_data_matplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QIGLU3q9ig9aeBPK_ojIDToQscsNNGOY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv(
    'https://raw.githubusercontent.com/teeloren/freecodecamp/main/adult.data.csv')

sal = data[data['salary'] == '>50K']
high_sal = sal['age']

plt.figure(figsize=(20, 10), dpi=300)
plt.hist(high_sal)
plt.xlabel('age')
plt.ylabel('total')
plt.title('Age of Salary Earners Making 50K+')
# plt.grid(axis='y',color='y',lw='1')
plt.show()

plt.figure(figsize=(20, 8), dpi=300)
plt.scatter(data['marital-status'], data['hours-per-week'])
plt.xlabel('marital-status', c='r')
plt.ylabel('hours-per-week', c='r')
plt.title('Hours Worked Per Week by Marital Status', c='r')
plt.grid(color='b', linestyle=':', linewidth='0.75')
plt.show()

labels = ['White', 'Black', 'Asian-Pac-Islander',
          'Amer-Indian-Eskimo', 'Other']
colors = ["g", "b", "c", "#f07c3a", "#6642f5"]
explode = (0, 0.1, 0.2, 0.4, 0.6)
plt.figure(figsize=(20, 10), dpi=300)
plt.pie(sal['race'].value_counts(), labels=labels,
        colors=colors, explode=explode, autopct='%1.1f%%')
plt.legend(labels=labels, bbox_to_anchor=(1, 1))
plt.title("Earners Making Over 50K by Race")
plt.show()

plt.style.use('seaborn')
plt.figure(figsize=(40, 10),  dpi=300)
labels = ['Married-civ-spouse', 'Never-married', 'Divorced',
          'Widowed', 'Separated', 'Married-spouse-absent', 'Married-AF-spouse']
plt.bar(sal['marital-status'], sal['age'])
plt.xlabel("Age")
plt.ylabel('Marital-status')
plt.title('Age by Marital-status')
# plt.legend(labels=labels, bbox_to_anchor=(1, 1))
# plt.grid()
plt.show()

# RangeIndex: 32561 entries, 0 to 32560
# Data columns (total 15 columns):
#  #   Column          Non-Null Count  Dtype
# ---  ------          --------------  -----
#  0   age             32561 non-null  int64    ++
#  1   workclass       32561 non-null  object   (9)
#  2   fnlwgt          32561 non-null  int64    ++
#  3   education       32561 non-null  object   (10)
#  4   education-num   32561 non-null  int64    (16)
#  5   marital-status  32561 non-null  object   (6)
#  6   occupation      32561 non-null  object   (15)
#  7   relationship    32561 non-null  object   (6)
#  8   race            32561 non-null  object   (5)
#  9   sex             32561 non-null  object   (2)
#  10  capital-gain    32561 non-null  int64    ++
#  11  capital-loss    32561 non-null  int64    ++
#  12  hours-per-week  32561 non-null  int64    ++
#  13  native-country  32561 non-null  object   ++
#  14  salary          32561 non-null  object   (2)
# dtypes: int64(6), object(9)
